# Generated by Django 4.2.23 on 2025-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="photos",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
